# run make test for python

name: Python Tests

on:
  - pull_request

jobs:
  python-translations:
    runs-on: ubuntu-latest

    steps:
      # Clones the openedx-translations repo
      - name: clone Zeit-Labs/openedx-translations
        uses: actions/checkout@v3

      - name: Install gettext
        run: |
          sudo apt install -y gettext

      # Sets up Python
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Run the script
      - name: run python tests
        run: |
          make test_requirements
          make test
